[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build", "npm run db:generate"]

[start]
cmd = "npm run db:migrate && npm start"
